### PR TITLE
feat: set compatibility with `--podman-version`

### LINKED ISSUE #45: [Feat. Req.] Add option to support older podman versions?
Many point-release distros may ship older versions of podman. It would be nice if the newest version of podlet can generate a quadlet file that's compatible with an older version of podman on demand with an option. Something like this:

```bash
podlet --compat=4.6 compose
```

---

On the technical side, I know of the [obake](https://github.com/doctorn/obake) crate that allows versioned structs. Perhaps this is something worth looking into, although I cannot say for sure how applicable it will be to this specific situation.

### PR DESCRIPTION
**Pull request by k9withabone**
Closes #45

Setting a lower podman version will downgrade generated quadlets compatibility. Will return an error if an incompatible quadlet option is used.

Implemented as an in-place, one-way transformation of `quadlet::File` and its parts. That way, there is less complexity than dealing with multiple versions of each quadlet resource type.

`--podman-version` has aliases `--compatibility` and `--compat`.

### CODE REVIEW

**Comment by k9withabone** [comment]
@cyqsimon, can you test this out and see if it fits with what you wanted?

**Comment by cyqsimon** [comment]
I tested on a few different compose files and it's looking great. The code looks pretty much like what I imagined too. I have no complaints whatsoever.

Thank you so much for swiftly taking on the feature request!

**Comment by cyqsimon** [comment]
Oh yes. I noticed that you probably want to update README, in particular the FEATURES and CAUTIONS sections.

**Comment by k9withabone** [comment]
Will do when I'm getting ready to release the next podlet version.

**Pull request merged**
